### ISSUE TITLE
About publishing instruction 

### ISSUE THREAD

**Issue by taneraruk** [niasla/Master-Thesis#1]
hi,

You said that "Under Migration, soon I'll publish the instructions to run the code." When do you plan to publish instruction?

thnks.

**Comment by niasla** [comment]
Hi taneruk,
sorry for this so long delay but the code became obsolete and I didn't maintain it although my plans were others. Sorry for the inconveniences and I shall remove that repo from here.

**Comment by taneraruk** [comment]
thanks for your information.
